name: Pytest (Cross platform, but x64 only)

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} for ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install .[dev]

    - name: Install tailwind binary
      run: |
        OS_NAME="${{ matrix.os }}"
        OS_NAME="${OS_NAME%-latest}"

        case "$OS_NAME" in
          ubuntu) OS_NAME="linux" ;;
        esac

        echo "OS_NAME --> $OS_NAME" # debug debug debug debug debug debug debug debug debug debug debug debug

        python scripts/binary.py pull $OS_NAME-x64
        python scripts/binary.py select $OS_NAME-x64

    - name: Run ruff and pytest
      run: |
        ruff check .
        pytest -v